package tn.stage.backend.Classes;

public enum EmployeeStatus {
    REQUEST_CREATED,
    RECRUITMENT_IN_PROGRESS,
    RECRUITED,
    CONTRACT_CREATED,
    INFRASTRUCTURE_ASSIGNED,
    PAYROLL_CALCULATED,
    FINANCE_VALIDATED,
    REVISION_REQUESTED,
    CLIENT_APPROVED,
    ACTIVE,
    CONTRACT_FINISHED,
    TERMINATED
}