spring.application.name=backend
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:stage_db}
spring.datasource.username=${POSTGRES_USER:stage_user}
spring.datasource.password=${POSTGRES_PASSWORD:mayssa@project}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=http://localhost:5173

google.client-id=423143793489-i96itnuqbc1lrl3r4fhjiqpmvm25qker.apps.googleusercontent.com

spring.mail.username=shophoria0@gmail.com
spring.mail.password=eeyozvxewrezooep


